# Generated by Django 3.2.7 on 2021-10-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together={('ingred', 'recipe_id')},
        ),
    ]
