# Generated by Django 3.2.7 on 2021-10-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_follow_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('subscriber', 'subscribed_to')},
        ),
    ]
